/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(async_ber_calculator.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3475b37363fe3bc97bf4b0951fd93105)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ber/async_ber_calculator.h>
// pydoc.h is automatically generated in the build directory
#include <async_ber_calculator_pydoc.h>

void bind_async_ber_calculator(py::module& m)
{

    using async_ber_calculator    = gr::ber::async_ber_calculator;


    py::class_<async_ber_calculator, gr::hier_block2,
        std::shared_ptr<async_ber_calculator>>(m, "async_ber_calculator", D(async_ber_calculator))

        .def(py::init(&async_ber_calculator::make),
           py::arg("sequence"),
           D(async_ber_calculator,make)
        )
        



        ;




}








